DROP TABLE IF EXISTS "mails_has_tags";
DROP TABLE IF EXISTS "ai_usage";
DROP TABLE IF EXISTS "mail_recipients";
DROP TABLE IF EXISTS "attachments";
DROP TABLE IF EXISTS "mail";
DROP TABLE IF EXISTS "folders";
DROP TABLE IF EXISTS "tags";
DROP TABLE IF EXISTS "users";


CREATE TABLE "users" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "firstname" TEXT NOT NULL,
    "lastname" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "birthdate" DATE NOT NULL,
    "credit_ai" INT NOT NULL DEFAULT 0,
    "role" TEXT NOT NULL DEFAULT 'user',
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "folders" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "user_id" INT NOT NULL,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE "mail" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT NOT NULL,
    "folder_id" INT NOT NULL,
    "read_at" TIMESTAMP,
    "sended_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "received_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "subject" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "sender_email" TEXT NOT NULL,
    "sender_name" TEXT,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    FOREIGN KEY ("folder_id") REFERENCES "folders"("id") ON DELETE CASCADE
);

CREATE TABLE "attachments" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "mail_id" INT NOT NULL,
    "filename" TEXT NOT NULL,
    "filesize" INT NOT NULL,
    "filepath" TEXT NOT NULL UNIQUE,
    FOREIGN KEY ("mail_id") REFERENCES "mail"("id") ON DELETE CASCADE
);

CREATE TABLE "mail_recipients" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "mail_id" INT NOT NULL,
    "recipient_email" TEXT NOT NULL,
    "recipient_type" TEXT NOT NULL,
    FOREIGN KEY ("mail_id") REFERENCES "mail"("id") ON DELETE CASCADE
);

CREATE TABLE "tags" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "color" TEXT NOT NULL,
    "user_id" INT NOT NULL,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE "mails_has_tags" (
    "mail_id" INT NOT NULL,
    "tag_id" INT NOT NULL,
    PRIMARY KEY ("mail_id", "tag_id"),
    FOREIGN KEY ("mail_id") REFERENCES "mail"("id") ON DELETE CASCADE,
    FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE
);

CREATE TABLE "ai_usage" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT NOT NULL,
    "feature" TEXT NOT NULL,
    "cost" INT NOT NULL,
    "tokens_used" INT NOT NULL,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);